version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.proxy
      args:
        - HTTP_PROXY=http://172.16.2.254:3128
        - HTTPS_PROXY=http://172.16.2.254:3128
    ports:
      - 3025:3025
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - NODE_ENV=development
      - CHOKIDAR_INTERVAL=300
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./src:/app/src  # Mount src directory for hot reload
      - ./public:/app/public  # Mount public directory for hot reload
      - ./package.json:/app/package.json  # Mount package.json
      - ./package-lock.json:/app/package-lock.json  # Mount package-lock.json
      - ./tailwind.config.ts:/app/tailwind.config.ts  # Mount tailwind.config.ts
      - ./src/app/globals.css:/app/src/app/globals.css  # Mount globals.css
      - ./tsconfig.json:/app/tsconfig.json  # Mount tsconfig.json
      - ./prisma:/app/prisma  # Mount prisma
      - ./node_modules:/app/node_modules
      - ./.env:/app/.env
      - ./next.config.mjs:/app/next.config.mjs
    networks:
      - web-network
    command: sh -c "npm rebuild && npm run dev"

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: zirospace
    ports:
      - "5433:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - web-network


networks:
  web-network:
    driver: bridge

volumes:
  postgres-data:
