FROM node:20.11-alpine3.19


WORKDIR /app

COPY package*.json ./

RUN npm config set proxy $HTTP_PROXY && \
    npm config set https-proxy $HTTPS_PROXY && \
    npm config set registry https://registry.npmjs.org/


RUN npm install 

COPY . .

RUN npx prisma generate

EXPOSE 3025

CMD ["npm", "run", "dev"] 
