-- Supabase SQL seed script for zirospace_services_en table

INSERT INTO zirospace_services_en (id, slug, title, subtitle, content_html, excerpt, image_url, image_alt, meta_title, meta_description, keywords, is_published, order_index, created_at, updated_at) VALUES
('1', 'service-1', 'Web Development', 'Building modern and responsive websites', '<p>We specialize in creating custom web solutions tailored to your business needs. From simple landing pages to complex web applications, we use the latest technologies to deliver high-quality results.</p><p>Our services include front-end development, back-end development, API integrations, and content management systems.</p>', 'Expert web development services.', 'https://picsum.photos/id/1015/800/600', 'Web Development Image', 'Web Development Services | Zirospace', 'Get professional web development services from Zirospace.', '["web development", "website design", "frontend", "backend", "CMS"]', true, 0, NOW(), NOW()),
('2', 'service-2', 'Mobile App Development', 'Creating intuitive and powerful mobile applications', '<p>Bring your ideas to life with our mobile app development services. We build native and cross-platform applications for iOS and Android, focusing on user experience and performance.</p><p>Whether you need a consumer-facing app or an enterprise solution, we have the expertise to deliver.</p>', 'Innovative mobile app solutions.', 'https://picsum.photos/id/1025/800/600', 'Mobile App Development Image', 'Mobile App Development | Zirospace', 'Develop your next mobile app with Zirospace.', '["mobile development", "iOS", "Android", "react native", "flutter"]', true, 1, NOW(), NOW()),
('3', 'service-3', 'Cloud Solutions', 'Scalable and secure cloud infrastructure', '<p>Leverage the power of the cloud with our comprehensive cloud solutions. We help you design, deploy, and manage your infrastructure on leading cloud platforms like AWS, Azure, and Google Cloud.</p><p>Our services cover cloud migration, infrastructure as code, serverless computing, and cloud security.</p>', 'Cloud infrastructure and management.', 'https://picsum.photos/id/1035/800/600', 'Cloud Solutions Image', 'Cloud Solutions | Zirospace', 'Migrate and manage your infrastructure in the cloud.', '["cloud computing", "AWS", "Azure", "Google Cloud", "serverless"]', true, 2, NOW(), NOW()),
('4', 'service-4', 'Data Analytics', 'Turning data into actionable insights', '<p>Unlock the value of your data with our data analytics services. We help you collect, process, and analyze data to gain valuable insights and make data-driven decisions.</p><p>Our expertise includes data warehousing, ETL pipelines, business intelligence, and machine learning.</p>', 'Data analysis and insights.', 'https://picsum.photos/id/1045/800/600', 'Data Analytics Image', 'Data Analytics Services | Zirospace', 'Get actionable insights from your data with Zirospace.', '["data analytics", "business intelligence", "ETL", "data warehousing", "machine learning"]', true, 3, NOW(), NOW()),
('5', 'service-5', 'UI/UX Design', 'Designing user-centered digital experiences', '<p>Create engaging and intuitive digital products with our UI/UX design services. We focus on understanding your users and designing interfaces that are both aesthetically pleasing and easy to use.</p><p>Our process includes user research, wireframing, prototyping, and usability testing.</p>', 'User interface and experience design.', 'https://picsum.photos/id/1055/800/600', 'UI/UX Design Image', 'UI/UX Design | Zirospace', 'Design user-friendly digital products with Zirospace.', '["UI design", "UX design", "user research", "prototyping", "usability testing"]', true, 4, NOW(), NOW()),
('6', 'service-6', 'SEO Optimization', 'Improving your search engine ranking', '<p>Increase your online visibility and drive organic traffic with our SEO optimization services. We analyze your website and implement strategies to improve your ranking on search engines like Google.</p><p>Our services include keyword research, on-page optimization, off-page optimization, and technical SEO.</p>', 'Boost your search engine ranking.', 'https://picsum.photos/id/1065/800/600', 'SEO Optimization Image', 'SEO Optimization Services | Zirospace', 'Improve your website\'s search engine ranking.', '["SEO", "search engine optimization", "keyword research", "on-page SEO", "off-page SEO"]', true, 5, NOW(), NOW()),
('7', 'service-7', 'Content Marketing', 'Creating valuable and engaging content', '<p>Attract and retain your target audience with our content marketing services. We develop content strategies and create high-quality content that resonates with your users and drives engagement.</p><p>Our services include blog posts, articles, whitepapers, case studies, and social media content.</p>', 'Engaging content for your audience.', 'https://picsum.photos/id/1075/800/600', 'Content Marketing Image', 'Content Marketing | Zirospace', 'Create compelling content with Zirospace.', '["content marketing", "blogging", "copywriting", "whitepapers", "case studies"]', true, 6, NOW(), NOW()),
('8', 'service-8', 'E-commerce Development', 'Building online stores that convert', '<p>Launch and grow your online business with our e-commerce development services. We build robust and scalable online stores using platforms like Shopify, WooCommerce, and custom solutions.</p><p>Our services cover store setup, product management, payment gateway integration, and security.</p>', 'Develop your online store.', 'https://picsum.photos/id/1085/800/600', 'E-commerce Development Image', 'E-commerce Development | Zirospace', 'Build a successful online store with Zirospace.', '["e-commerce", "online store", "Shopify", "WooCommerce", "payment gateway"]', true, 7, NOW(), NOW()),
('9', 'service-9', 'Digital Marketing Strategy', 'Developing a comprehensive online presence', '<p>Create a winning online presence with our digital marketing strategy services. We analyze your business and target audience to develop a tailored strategy that combines various digital channels.</p><p>Our services include market research, competitor analysis, channel selection, and performance tracking.</p>', 'Comprehensive digital marketing plans.', 'https://picsum.photos/id/1095/800/600', 'Digital Marketing Strategy Image', 'Digital Marketing Strategy | Zirospace', 'Plan your digital success with Zirospace.', '["digital marketing", "marketing strategy", "online presence", "competitor analysis", "market research"]', true, 8, NOW(), NOW()),
('10', 'service-10', 'IT Consulting', 'Expert advice for your technology needs', '<p>Get expert guidance on your technology decisions with our IT consulting services. We help you evaluate your current infrastructure, identify areas for improvement, and recommend solutions that align with your business goals.</p><p>Our services cover technology assessment, strategic planning, vendor selection, and project management.</p>', 'Expert IT guidance.', 'https://picsum.photos/id/1100/800/600', 'IT Consulting Image', 'IT Consulting Services | Zirospace', 'Get expert IT advice from Zirospace.', '["IT consulting", "technology strategy", "infrastructure assessment", "project management", "vendor selection"]', true, 9, NOW(), NOW());

-- images to use https://picsum.photos/200/300 https://picsum.photos/200/300