-- Create the 'apps' table
CREATE TABLE public.apps (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying NOT NULL,
    description text,
    thumbnail_url character varying,
    average_rating double precision DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Create the 'screenshots' table
CREATE TABLE public.screenshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id bigint NOT NULL REFERENCES public.apps(id) ON DELETE CASCADE,
    image_url character varying NOT NULL,
    screen_name character varying,
    route_path character varying,
    description text,
    order_index integer DEFAULT 0,
    average_rating double precision DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Create the 'app_ratings' table
CREATE TABLE public.app_ratings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id bigint NOT NULL REFERENCES public.apps(id) ON DELETE CASCADE,
    user_id character varying, -- Nullable for anonymous ratings
    rating_value integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Create the 'screenshot_ratings' table
CREATE TABLE public.screenshot_ratings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screenshot_id bigint NOT NULL REFERENCES public.screenshots(id) ON DELETE CASCADE,
    user_id character varying, -- Nullable for anonymous ratings
    rating_value integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
